services:
    api:
        container_name: embed_worker
        build:
            context: .
            dockerfile: ./app/Dockerfile

        volumes:
            - ./logs:/var/log/cronlogs

        network_mode: "host"
