services:
    api:
        container_name: embed_worker
        build:
            context: .
            dockerfile: ./app/Dockerfile

        volumes:
            - ./logs:/var/log/cronlogs

        depends_on:
            - ollama

    ollama:
        image: ollama/ollama
        ports:
            - 11434:11434





